"""message

Revision ID: f7f5835242ab
Revises: 1369a0757da6
Create Date: 2024-07-04 21:11:56.317743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f5835242ab'
down_revision = '1369a0757da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
